language: scala
branches:
  only:
  - master
before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C
  /tmp/
- git clone https://github.com/ryanbrainard/heroku-buildpack-testrunner.git /tmp/testrunner
- ./etc/hatchet_travis_setup.sh
install: true
script: eval "$TEST_CMD"
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - IS_RUNNING_ON_TRAVIS=true
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-scala.git"
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  - secure: uG5As4RmfkPH4OPpUzRujjYGZF3LXDD07tbDZLB1uMqcmYO4F6L7Dw6xr2hDl5LK905sTzu1VPt445KDp4ygjHyjwOXtyt11bPn2y79M1ilDv6oeGyYGlZXF1qW7urwTmwi2imt2+XNPTvnE0pT8KJVsUt6w/6zOkdkf+Z2qAME=
  matrix:
  - TEST_CMD='[ "$TRAVIS_PULL_REQUEST" = "false" ] && sbt hatchet || true'
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
